# railway.toml

[project]
name = "streaming-voice-agent"
description = "FastAPI server for Vosk ASR + GPT4All + Google TTS"

[service]
name = "server"
type = "web"
build = "python"
start = "gunicorn -w 4 -b 0.0.0.0:$PORT main:app"

[env]
GOOGLE_API_KEY = "your_google_api_key_here"
DG_API_KEY = "your_deepgram_api_key_here"

[deploy]
command = "pip install -r requirements.txt"
